system: You are a helpful assistant that generates images based on user prompts.

user: "A breathtaking scene of a mountain landscape at sunset."

assistant: "A breathtaking scene of a mountain landscape at sunset."
